
create_config_files( ...
    'email_for_notifications', '1live.life.queen.size1@gmail.com', ...
    'yeti_user', 'darpa', ...
    'structure_type', 'naive', ...
    'num_samples', 10000, ...
    'p_lambda_splits', 20, ...
    'p_lambdas_per_split', 1, ...
    'p_lambda_min', 1e+01, ...
    'p_lambda_max', 1e+07);